// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideogameStore.Data;

#nullable disable

namespace VideogameStore.Data.Migrations
{
    [DbContext(typeof(VideogameStoreDbContext))]
    [Migration("20260707065437_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideogameStore.Data.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Address = "Harmond street 134",
                            Email = "Juan@example.com",
                            Name = "Juan",
                            SurName = "Lopez"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Address = "Julieth street 3",
                            Email = "Mario@example.com",
                            Name = "Mario",
                            SurName = "Rosa"
                        });
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentMethodId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("StoreId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Sale_Detail", b =>
                {
                    b.Property<int>("Sale_DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Sale_DetailId"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VideogameId")
                        .HasColumnType("int");

                    b.HasKey("Sale_DetailId");

                    b.HasIndex("SaleId");

                    b.HasIndex("VideogameId");

                    b.ToTable("Sale_Details");
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoreId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            StoreId = 1,
                            Address = "James Bond street 77",
                            EmployeeId = 1,
                            StoreName = "Gamestop"
                        },
                        new
                        {
                            StoreId = 2,
                            Address = "Abraham's lincon street 44",
                            EmployeeId = 2,
                            StoreName = "Gamestop 2"
                        });
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Videogame", b =>
                {
                    b.Property<int>("VideogameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideogameId"));

                    b.Property<string>("Gamename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("VideogameId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            VideogameId = 1,
                            Gamename = "Super Smash Bros Ultimate",
                            Genre = "Fighting",
                            Rating = 0,
                            Stock = 10
                        },
                        new
                        {
                            VideogameId = 2,
                            Gamename = "The Legend Of Zelda Ocarina Of Time",
                            Genre = "Adventure",
                            Rating = 1,
                            Stock = 6
                        },
                        new
                        {
                            VideogameId = 3,
                            Gamename = "Hollow Knight: Silksong",
                            Genre = "2D Platformer",
                            Rating = 1,
                            Stock = 5
                        });
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Videogame_Store", b =>
                {
                    b.Property<int>("Videogame_StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Videogame_StoreId"));

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<int>("VideogameId")
                        .HasColumnType("int");

                    b.HasKey("Videogame_StoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("VideogameId");

                    b.ToTable("GameStore");

                    b.HasData(
                        new
                        {
                            Videogame_StoreId = 1,
                            StoreId = 1,
                            VideogameId = 1
                        },
                        new
                        {
                            Videogame_StoreId = 2,
                            StoreId = 2,
                            VideogameId = 2
                        });
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Sale", b =>
                {
                    b.HasOne("VideogameStore.Data.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameStore.Data.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideogameStore.Data.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameStore.Data.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Sale_Detail", b =>
                {
                    b.HasOne("VideogameStore.Data.Entities.Sale", "Sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VideogameStore.Data.Entities.Videogame", "Videogame")
                        .WithMany()
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sale");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Store", b =>
                {
                    b.HasOne("VideogameStore.Data.Entities.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("VideogameStore.Data.Entities.Store", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Videogame_Store", b =>
                {
                    b.HasOne("VideogameStore.Data.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideogameStore.Data.Entities.Videogame", "Videogame")
                        .WithMany()
                        .HasForeignKey("VideogameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("Videogame");
                });

            modelBuilder.Entity("VideogameStore.Data.Entities.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
